version: "3.8"

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    restart: unless-stopped
    ports:
      - "7474:7474" # Acesso ao Neo4j Browser
      - "7687:7687" # Porta do Bolt (usado por drivers)
    environment:
      - NEO4J_AUTH=${NEO4J_USERNAME:-neo4j}/${NEO4J_PASSWORD:-password}
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_conf:/var/lib/neo4j/conf

  nodeflow:
    image: marcoseduardoss/nodeflow:latest
    container_name: nodeflow
    restart: unless-stopped
    depends_on:
      - neo4j
    ports:
      - "8080:8080" # Porta do doc, backend e frontend
    environment:
      - NEO4J_URI=${NEO4J_URI:-bolt://neo4j:7687}
      - NEO4J_USERNAME=${NEO4J_USERNAME:-neo4j}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD:-password}
      - NEO4J_DATABASE=${NEO4J_DATABASE:-neo4j}

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_conf:
